version: "3.4"

services:
  web:
    container_name: python3.9
    build:
      context: docker
      dockerfile: docker/Dockerfile
    volumes:
      - ./app:/code/app:z
    ports:
      - "80:80"
    tty: true
  db:
    image: postgres:13.3
    container_name: postgres13.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"